### ISSUE TITLE
[Enhancement] Upcoming GameScope Filtering Changes

### ISSUE THREAD

**Issue by sonic2kk** [sonic2kk/steamtinkerlaunch#838]
## System Information
- SteamTinkerLaunch version: git
- Distribution: Arch Linux

## Feature Description
GameScope in git has changed how it takes upscaling and filtering arguments. The existing `-Y`, `U`, and `-n` flags for NIS, FSR and Integer Scaling respectively have been **removed** and **replaced** with the following ([as noted on the Readme](https://github.com/ValveSoftware/gamescope/blob/7a1fe2def38e9c3ed4d12adb9f1bb81b6f9dcbe5/README.md?plain=1#L66-L69) as of the latest commit at time of writing: ValveSoftware/gamescope@7a1fe2def38e9c3ed4d12adb9f1bb81b6f9dcbe5):
- `-F <filter>`, where `<filter>`  can be `linear`, `nearest`, `nis`, `fsr`
- `-S <scale>`, where `<scale>` can be `auto`, `integer`, `fit`, `fill`, `stretch`.

Since this is in git, some STL users may be affected. In future when this makes it into a stable release, this will affect all STL users making use of GameScope. That is, once those users update and a newer version is available to them (package managers, etc).

<hr>

STL will need to update in the meanwhile to accommodate **both** the old *and new* usage, STL will need to make some changes:
- Check the GameScope manpage and make some assumptions about the GameScope version used (if it has the new vs. old docs we can make assumptions about what syntax to use)
- Update to accomodate the new syntax
- Add support for the (new?) `stretch` option.

I am not sure of the depth required for these changes. I am hoping that the overhaul to GameScope (#744) will make this a bit smoother.

These changes will stay in a branch for a while to give these changes a chance to "settle" upstream, in case there are any changes in the meanwhile to account for.

<hr>

I am opening this issue to remind myself that this change will be required ASAP. To test, I will test against builds of GameScope before and after the commit for this refactor.

TODO:
- [x] Refactor UI to use dropdowns for scaling and filtering options instead of checkboxes
- [x] Refactor code to allow `-F` for setting FSR, NIS, and Nearest Neighbor *if* the current GameScope help screen uses those options
- [x] Refactor code to allow `-S` for setting Integer scaling
- [x] Investigate support for new Filter option: `linear` (probably default so might not be needed)
- [x] Investigate support for new scale options: `fit`, `fill`, and `stretch`
- [x] Investigate support for `auto` scale (probably default so might not be needed)

**Comment by sonic2kk** [comment]
This commit ValveSoftware/gamescope@789cfc90575a7dbfc61ffa3325a4fb7f59f4d8b5 is very interesting:

> No window system, vr, drm, etc required.
> 
> Can be used to stream headlessly with Pipewire or screenshots, etc.
> 
> Can also just be used as a utility to run applications that need a GUI
> or window envrionment despite just being an installer or something.

Particularly the last statement, this could be pretty nifty. We can add this option under the advanced settings.

**Comment by sonic2kk** [comment]
Headless option was added in #843.

**Comment by sonic2kk** [comment]
Having thought about it some more, the UI will need to be entirely redone. We'll probably need a dropdown for scaler and filter type, to replace the checkboxes we have currently. These new options for scaler and filter mean that unlike before, **we cannot use all the different scaler/filter types at once with different flags**. The user can only use, for example, FSR *or* NIS, not both like they could when passing `-U -Y`.

We should still be able to accomodate both old and new users this way. The issue is that this will be a **breaking change** for users who are currently using filtering with GameScope, as they'll need to reconfigure their arguments on the menu. Maybe I should add a Defaults button for GameScope like we have for One-Time Run...

Having a dropdown for the options should simplify the process significantly. The way sharpness is passed remains unchanged (though we can probably remove the checks for `--fsr-sharpness` and `--sharpness`.

Overhauling the UI again is gonna be a bit of a pain, especially with `GSARR` shuffling. A bunch of lang strings can probably be removed too. This one will be a big oof and may be the last major "feature" I work on for a while.

**Comment by sonic2kk** [comment]
Defaults button was added in #844. This should make it easier to reset existing GameScope configurations once the UI overhaul is implemented.

**Comment by sonic2kk** [comment]
The GameScope GUI is being refactored to use Combobox Entry fields for the new Filter/Scaler options. I chose this over regular Comboboxes in case GameScope updates to add new filters. Then we won't need to update the list of dropdowns with an STL version bump, a user can just enter the name of the filter/scaler.

**Comment by sonic2kk** [comment]
This functionality is ready in #845, it is feature-complete. I am holding off on merging for now to update the wiki and to make sure there are no additional changes upstream. I'll probably merge in a week max.

The `linear` filter option and `auto` scale option were added in the dropdown, but `none` is the default (if the input fields are blank, we fall back to `none` as well). A user can still select `linear` and `scale` in the dropdown and it will get passed, but by default no option is passed.

Users can also enter any custom values if they want too. They might not always be recognised by GameScope, though.

**Comment by sonic2kk** [comment]
#845 was merged, this can be closed.
